### ISSUE TITLE
can't use the program from Ipad

### ISSUE THREAD

**Issue by pbranly** [Smeagolworms4/MQTT-Explorer#1]
Hi,
I tried to install the program inside a docker.
My configuration is as follow:
` define a mqtt-explorer service

  mqtt-explorer:
    container_name: Mqtt-explorer
    image: smeagolworms4/mqtt-explorer:latest
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./mqtt-explorer/config:/mqtt-explorer/config
    ports:
      - 4001:4000

`
It works very well from my Windows computer using localaddress:4001 and can connect to my mqt server
It works and connects as well from my Ipad but left main screen stays blank.
It seems to be an IOS issue
Regards
Phil

**Comment by gilmrt** [comment]
Seems to be an issue with Safari browser
I get the same result with no details using Safari
It works fine using Chrome
MQTT Connection page works, then once connected no details and I got error message "Ooooooops !" with logs below

`cleanup@http://192.168.1.6:4000/3.bundle.js:25338:38
Hi@http://192.168.1.6:4000/vendors.bundle.js:15155:158
Vj@http://192.168.1.6:4000/vendors.bundle.js:15201:297
@http://192.168.1.6:4000/vendors.bundle.js:15274:468
yj@http://192.168.1.6:4000/vendors.bundle.js:15183:102
yj@[native code]
@http://192.168.1.6:4000/vendors.bundle.js:15067:116
@http://192.168.1.6:4000/vendors.bundle.js:15274:468
fg@http://192.168.1.6:4000/vendors.bundle.js:15067:63
gg@http://192.168.1.6:4000/vendors.bundle.js:15066:498
Mj@http://192.168.1.6:4000/vendors.bundle.js:15184:68
notify@http://192.168.1.6:4000/vendors.bundle.js:1116:12
notifyNestedSubs@http://192.168.1.6:4000/vendors.bundle.js:1189:26
handleChangeWrapper@http://192.168.1.6:4000/vendors.bundle.js:1194:25
handleChangeWrapper@[native code]
dispatch@http://192.168.1.6:4000/vendors.bundle.js:595:15
dispatchChildActions@http://192.168.1.6:4000/app.bundle.js:17491:21
@http://192.168.1.6:4000/app.bundle.js:17488:29
forEach@[native code]
dispatchChildActions@http://192.168.1.6:4000/app.bundle.js:17487:29
@http://192.168.1.6:4000/app.bundle.js:17498:29
@http://192.168.1.6:4000/app.bundle.js:6180:17
invokeFunc@http://192.168.1.6:4000/app.bundle.js:48109:24
trailingEdge@http://192.168.1.6:4000/app.bundle.js:48156:24
timerExpired@http://192.168.1.6:4000/app.bundle.js:48144:26`

**Comment by pbranly** [comment]
Hi before trying again,is there any news about that issue ?
Phil

**Comment by pbranly** [comment]
The new today version works now
Thank you very much 
Phil
